### ISSUE TITLE
use `.env` instead of `.rbenv-vars` file

### ISSUE THREAD

**Issue by tammersaleh** [rbenv/rbenv-vars#13]
This is related to #12, but I was wondering if there was a good argument to be made for (or against) using a more standardish `.env` file to hold the variables instead of the rbenv-specific `rbenv-vars` file.

Seems like that would be beneficial to Foreman users.

**Comment by jasonkarns** [comment]
@tsaleh ever do a generic dotenv plugin?

If so, I strongly suggest following @bkeepers dotenv file format, which is the basis for a [ruby gem](https://github.com/bkeepers/dotenv) as well as an [npm module](https://github.com/motdotla/dotenv).

**Comment by tsaleh** [comment]
@jasonkarns Thanks for the suggestion, but I never did get around to this.  Don't really use ruby much anymore, so unlikely to hit this any time soon.

**Comment by jasonkarns** [comment]
@tsaleh do you use node? I'm selfishly hoping for this feature so I can port it to [nodenv](https://github.com/OiNutter/nodenv) and [nodenv-vars](https://github.com/OiNutter/nodenv-vars). :)

**Comment by tsaleh** [comment]
The few times I'm allowed to code, nowadays, I've been using Go :-/
