### ISSUE TITLE
"/dev/fd/62: No such file or directory" after installing rbenv-vars on FreeBSD

### ISSUE THREAD

**Issue by buildc0de** [rbenv/rbenv-vars#19]
This appears to be the same as https://github.com/sstephenson/rbenv/issues/401 :smiling_imp: Will submit a pull request in a bit.

**Comment by karlingen** [comment]
...aaaand it was never submitted.

**Comment by gregnavis** [comment]
Thanks @waywalker for submitting the PR. What needs to happen in order to merge this PR? I'd be happy to devote a few hours of my time ot make this happen.

**Comment by waywalker** [comment]
Sounds great! https://github.com/rbenv/rbenv-vars/pull/20 is ready to be merged in :-)
