### ISSUE TITLE
Should alternatively look for `.ruby-env` 

### ISSUE THREAD

**Issue by myers** [rbenv/rbenv-vars#25]
rvm will read env vars from `.ruby-env`

https://github.com/rvm/rvm/issues/2105

It would be nice if rbenv-vars did the same, perhaps first checking `.rbenv-vars`.

**Comment by mislav** [comment]
See https://github.com/sstephenson/rbenv-vars/issues/13#issuecomment-30332123

**Comment by mislav** [comment]
Closing as wontfix, but thank you for the feature idea!
