### ISSUE TITLE
Escaping quotes for variables that needs to be quoted

### ISSUE THREAD

**Issue by lenart** [rbenv/rbenv-vars#29]
I had (weird) problems setting up rbenv-vars and my rails application to work. I was getting errors for random gems - like this `There was an error while trying to load the gem 'delayed_job_active_record'`. It turned out the problem occurred because of quotes in my .rbenv-vars and the way they were escaped. Because I had a `(` in my password I added quotes it in my `.rbenv-vars` like so:

```
DATABASE_URL="postgres://deployer:my(password@127.0.0.1:5432/database"
```

To simplify what's happening:

`VAR="foo(bar"` gets transformed by rbenv-vars to `export VAR='"foo(bar"'`. I've also tried using single quotes which makes the result even worst `'export VAR='\''production'\'''`.

Is it something I'm doing wrong or should this be solved by rbenv-vars somehow?

**Comment by mislav** [comment]
I'm not familiar with how rbenv-vars chooses to quote things, but for now it seems best to lose the double quotes and have rbenv-vars just single-quote everything.

**Comment by sstephenson** [comment]
Don’t put quotes around the value. It’s not necessary.

```
$ mkdir test; cd test
$ echo "DATABASE_URL=postgres://deployer:my(password@127.0.0.1:5432/database" > .rbenv-vars
$ ruby -e 'puts ENV["DATABASE_URL"]'
postgres://deployer:my(password@127.0.0.1:5432/database
```

**Comment by mislav** [comment]
I wouldn't close the issue just yet. I find it surprising that we're not able to use perfectly valid variable definition syntax `FOO="..."` in `.rbenv-vars` files. Couldn't it detect quotes and avoid single-quoting in that case?

**Comment by sstephenson** [comment]
rbenv-vars’ parser reads values from `=` to the end of the line and quotes them automatically.

Per the docs:
> Spaces are allowed in values; quoting is not necessary.

Might be best to tweak that language so it’s obvious that quotes will appear as literal quote characters in the value.

**Comment by lenart** [comment]
For the record - I couldn't boot up rails unless I added quotes around variable value.

**Comment by sstephenson** [comment]
That sounds like a problem with your application. The shell log in my previous comment demonstrates that the environment variable is set properly in the Ruby process.

You’re right that you need to quote the variable when setting it in your shell. Shell syntax and rbenv-vars syntax differ in this regard.
