### ISSUE TITLE
dotenv-rails collision

### ISSUE THREAD

**Issue by chrishough** [rbenv/rbenv-vars#34]
What is the common practice for collisions in local .env versus the global vars file?

**Comment by mislav** [comment]
Hi, sorry for the late reply. There is no common practice that I am aware. The `.rbenv-vars` is meant for Ruby applications only and is transparently loaded to any Ruby process started by rbenv. The `.env` file is explicitly loaded by all kinds of applications and is a more generalized approach to the same problem. For simplicity sake, you should not use both, and if you do, know that `.env` will probably overwrite variables in `.rbenv-vars`.

**Comment by chrishough** [comment]
Thank you
